### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/software-engineers

###
GET http://localhost:8080/software-engineers/1


###
POST http://localhost:8080/software-engineers
Content-Type: application/json

{
  "name": "Sam",
  "techStack": "js, node, spring"
}